data<-c(10,15,20,25,30,35,40,45,50)
print(data)
mean_value<-mean(data)
median_value<-median(data)
firstQ<-quantile(data,0.25)
thirdQ<-quantile(data,0.75)
min_value<-min(data)
max_value<-max(data)
Var_value<-var(data)

cat("Mean:",mean_value,"\n")
cat("median:",median_value,"\n")
cat("First Quantile:",firstQ,"\n")
cat("Third Quantile:",thirdQ,"\n")
cat("Minimum value:",min_value,"\n")
cat("Maximum value:",max_value,"\n")
cat("Variance:",Var_value,"\n")
plot(data)
boxplot(data, main="Boxplot of the Dataset", col="brown",xlab="Values", border="black",horizontal =TRUE)
data2<-c(15,18,23,34,49,53,64,75,86)
print(data2)
cor_value<-cor(data,data2)
cov_value<-cov(data,data2)
cat("Correalation between data and data2:",cor_value,"\n")
cat("Covariance between data and data2:",cov_value,"\n")